import { ArrowRight } from "lucide-react";
import { BOOKING_URL } from "../../lib/constants";
import { trackLead } from "../../lib/analytics";
import { FadeIn } from "../../components/motion/FadeIn";
import { Dot } from "../../components/brand/Dot";
import { AuditForm } from "../../components/AuditForm";

// Dedicated paid-traffic landing page for the Meta free-audit campaign.
// Kept separate from /lp/email (which is a direct-to-book £1,400 sales page):
// cold ad traffic converts on a low-commitment audit, not a paid-spot pitch.
// No sitewide Nav/Footer — every off-page link is a paid-click leak. noindex
// so it never competes with the money pages in search.

const OFFER = "email";

export const meta = () => [
  { title: "Free skincare email audit — EraLean" },
  {
    name: "description",
    content:
      "The 3 highest-leverage fixes for your UK skincare brand's email — free, specific to your store, delivered within one business day. No pitch.",
  },
  { name: "robots", content: "noindex, nofollow" },
];

/* ── Minimal header (logo only, no nav) ───────────────────────────────── */

function Header() {
  return (
    <header className="px-6 py-8 text-center">
      <span className="font-display tracking-display text-base font-semibold text-white">
        eralean<span className="text-volt">.</span>
      </span>
    </header>
  );
}

/* ── Hero: promise (left) + form above the fold (right) ───────────────── */

const TRUST = [
  "3 specific fixes, each mapped to revenue",
  "Delivered within one business day",
  "No pitch — the fixes are yours even if we never speak",
];

function Hero() {
  return (
    <section className="px-6 pb-16 pt-4 md:px-10 md:pb-24">
      <div className="mx-auto grid w-full max-w-6xl items-center gap-12 lg:grid-cols-2 lg:gap-16">
        {/* Promise */}
        <div>
          <FadeIn>
            <div className="inline-flex items-center gap-2.5 text-[11px] font-medium uppercase tracking-[0.24em] text-white/45">
              <Dot />
              Free skincare email audit
            </div>
          </FadeIn>

          <FadeIn delay={0.06}>
            <h1 className="mt-7 font-display tracking-display text-[clamp(2.5rem,5vw,4.25rem)] font-semibold leading-[1.0] text-white">
              The revenue hiding in your skincare email — mapped for free.
            </h1>
          </FadeIn>

          <FadeIn delay={0.12}>
            <p className="mt-7 max-w-[48ch] font-sans font-light text-white/55">
              Done-for-you Klaviyo for UK skincare &amp; beauty brands. Tell us
              your store and we'll send the three fixes we'd make first — the
              exact leaks costing you sales right now.
            </p>
          </FadeIn>

          <FadeIn delay={0.18}>
            <ul className="mt-9 space-y-3.5">
              {TRUST.map((item) => (
                <li key={item} className="flex items-start gap-3">
                  <Dot className="mt-2" />
                  <span className="font-sans font-light text-white/70">{item}</span>
                </li>
              ))}
            </ul>
          </FadeIn>

          <FadeIn delay={0.24}>
            <p className="mt-9 border-t border-white/10 pt-6 text-sm text-white/45">
              <span className="text-volt">£262K</span> generated by one welcome
              flow · <span className="text-volt">38.7%</span> open rate · UK
              skincare · Klaviyo
            </p>
          </FadeIn>
        </div>

        {/* Form — above the fold on desktop */}
        <FadeIn delay={0.1}>
          <AuditForm
            offer={OFFER}
            variant="embed"
            bare
            showQualifier
            heading="Get your 3 fixes"
            subtext="Your store and revenue below. We tailor the audit to your brand and send it within one business day. No spam, no pitch."
            button="Send my free audit"
          />
        </FadeIn>
      </div>
    </section>
  );
}

/* ── Proof bar ────────────────────────────────────────────────────────── */

function ProofBar() {
  const stats = [
    { metric: "38.7%", label: "Open rate on our flagship flow", context: "vs 20–25% industry average" },
    { metric: "£262K", label: "Generated by one welcome flow", context: "UK skincare brand · Klaviyo" },
    { metric: "71,059", label: "Emails delivered", context: "Same flow, Klaviyo UK" },
  ];

  return (
    <section className="border-t border-white/10 bg-carbon px-6 py-16 md:px-10 md:py-20">
      <FadeIn>
        <div className="mx-auto grid max-w-5xl grid-cols-1 gap-px bg-white/10 md:grid-cols-3">
          {stats.map((s) => (
            <div key={s.label} className="bg-carbon px-6 py-8 text-center md:py-4">
              <div className="font-display tracking-display text-[2.5rem] text-volt">{s.metric}</div>
              <div className="mt-3 font-sans font-light text-white">{s.label}</div>
              <div className="mt-1 text-sm text-white/45">{s.context}</div>
            </div>
          ))}
        </div>
      </FadeIn>
    </section>
  );
}

/* ── What's in your free audit ───────────────────────────────────────── */

function WhatsInIt() {
  const items = [
    {
      title: "Your welcome flow",
      body: "Where new subscribers drop off before they buy — and the emails that turn that first moment into first orders.",
    },
    {
      title: "Your abandoned-cart recovery",
      body: "The carts you're quietly losing at checkout, and the sequence that brings a meaningful share of them back.",
    },
    {
      title: "Your campaigns & segmentation",
      body: "Why blasting the whole list hurts deliverability, and the segments that lift revenue per send.",
    },
  ];

  return (
    <section className="border-t border-white/10 bg-ink px-6 py-24 md:px-10 md:py-32">
      <div className="mx-auto max-w-6xl">
        <FadeIn>
          <div className="flex items-center gap-2.5 text-[11px] font-medium uppercase tracking-[0.24em] text-white/45">
            <Dot />
            What's in your free audit
          </div>
          <h2 className="mt-5 font-display tracking-display text-3xl text-white md:text-4xl">
            Three fixes, mapped to revenue<span className="text-volt">.</span>
          </h2>
        </FadeIn>

        <div className="mt-12 grid gap-6 md:grid-cols-3">
          {items.map((c, i) => (
            <FadeIn key={c.title} delay={i * 0.07}>
              <div className="h-full rounded-2xl border border-white/10 bg-carbon p-8">
                <h3 className="font-display tracking-display text-xl text-white">{c.title}</h3>
                <p className="mt-4 font-sans font-light leading-relaxed text-white/55">
                  {c.body}
                </p>
              </div>
            </FadeIn>
          ))}
        </div>
      </div>
    </section>
  );
}

/* ── Secondary CTA — book a call now (for the high-intent minority) ───── */

function TalkNow() {
  return (
    <section className="border-t border-white/10 bg-carbon px-6 py-20 text-center md:px-10 md:py-24">
      <FadeIn>
        <div className="mx-auto max-w-2xl">
          <h2 className="font-display tracking-display text-2xl text-white md:text-3xl">
            Rather just talk it through?
          </h2>
          <p className="mx-auto mt-4 max-w-md font-sans font-light text-white/55">
            Skip the audit and book a free 20-minute call. Same honest read on
            your email — live, with your questions answered.
          </p>
          <a
            href={BOOKING_URL}
            target="_blank"
            rel="noopener noreferrer"
            onClick={() => trackLead(OFFER)}
            className="group mt-8 inline-flex items-center gap-2 rounded-full border border-white/20 px-8 py-4 font-display tracking-display text-base font-semibold text-white transition-colors hover:border-volt hover:text-volt"
          >
            Book a free 20-minute call
            <ArrowRight className="h-4 w-4 transition-transform group-hover:translate-x-0.5" />
          </a>
        </div>
      </FadeIn>
    </section>
  );
}

/* ── Footer ───────────────────────────────────────────────────────────── */

function MinimalFooter() {
  return (
    <footer className="bg-ink px-6 py-10 text-center">
      <p className="text-xs text-white/45">© 2026 EraLean · asaf@eralean.com</p>
    </footer>
  );
}

export default function AuditLp() {
  return (
    <div className="bg-ink text-white">
      <Header />
      <main>
        <Hero />
        <ProofBar />
        <WhatsInIt />
        <TalkNow />
      </main>
      <MinimalFooter />
    </div>
  );
}
