import { ArrowRight, ChevronDown } from "lucide-react";
import { trackLead } from "../../lib/analytics";
import { FadeIn } from "../../components/motion/FadeIn";
import { Dot } from "../../components/brand/Dot";

const CALENDLY_PLACEHOLDER = "https://calendar.app.google/2mmmEqFVPaLvZ6dy7";
const OFFER = "email";

export const meta = () => [
  { title: "Email Marketing for Ecommerce — EraLean" },
  {
    name: "description",
    content:
      "Klaviyo email management for ecommerce brands. Flows, campaigns, and deliverability — £490/month, 3 spots available.",
  },
  { name: "robots", content: "noindex, nofollow" },
];

function onCtaClick() {
  trackLead(OFFER);
}

/* ── Header ───────────────────────────────────────────────────────────── */

function Header() {
  return (
    <header className="px-6 py-8 text-center">
      <span className="font-display tracking-display text-base font-semibold text-white">
        eralean<span className="text-volt">.</span>
      </span>
    </header>
  );
}

/* ── Hero ─────────────────────────────────────────────────────────────── */

function Hero() {
  return (
    <section className="flex min-h-screen items-center px-6 py-20 md:px-10">
      <div className="mx-auto w-full max-w-3xl text-center">
        <FadeIn>
          <div className="inline-flex items-center gap-2.5 text-[11px] font-medium uppercase tracking-[0.24em] text-white/45">
            <Dot />
            Email marketing · 3 spots available
          </div>
        </FadeIn>

        <FadeIn delay={0.06}>
          <h1 className="mt-7 font-display tracking-display text-[clamp(2.8rem,6vw,5rem)] font-semibold leading-[0.98] text-white">
            Your email list is sitting on revenue you haven't collected yet.
          </h1>
        </FadeIn>

        <FadeIn delay={0.12}>
          <p className="mx-auto mt-7 max-w-[52ch] font-sans font-light text-white/55">
            We rebuild your Klaviyo flows from scratch — welcome, abandoned
            cart, post-purchase — and manage your campaigns every month. Most
            brands see results in the first 30 days.
          </p>
        </FadeIn>

        <FadeIn delay={0.18}>
          <div className="mt-9 flex flex-col items-center">
            <a
              href={CALENDLY_PLACEHOLDER}
              target="_blank"
              rel="noopener noreferrer"
              onClick={onCtaClick}
              className="group inline-flex w-full items-center justify-center gap-2 rounded-full bg-volt px-8 py-4 font-display tracking-display text-base font-semibold text-ink transition-colors hover:bg-[#a8e600] sm:w-auto"
            >
              Claim your spot — £490/month
              <ArrowRight className="h-4 w-4 transition-transform group-hover:translate-x-0.5" />
            </a>
            <p className="mt-4 text-sm text-white/45">
              3 spots available at this price. No lock-in contract.
            </p>
          </div>
        </FadeIn>
      </div>
    </section>
  );
}

/* ── Proof bar ────────────────────────────────────────────────────────── */

function ProofBar() {
  const stats = [
    { metric: "70%", label: "Average open rate", context: "Industry average: 20–25%" },
    { metric: "99.99%", label: "Deliverability rate", context: "Inbox, not spam" },
    { metric: "£262K", label: "Generated by one welcome flow", context: "Klaviyo — ecommerce brand, UK" },
  ];

  return (
    <section className="bg-carbon px-6 py-16 md:px-10 md:py-20">
      <FadeIn>
        <div className="mx-auto grid max-w-5xl grid-cols-1 gap-px bg-white/10 md:grid-cols-3">
          {stats.map((s) => (
            <div key={s.label} className="bg-carbon px-6 py-8 text-center md:py-4">
              <div className="font-display tracking-display text-[2.5rem] text-volt">{s.metric}</div>
              <div className="mt-3 font-sans font-light text-white">{s.label}</div>
              <div className="mt-1 text-sm text-white/45">{s.context}</div>
            </div>
          ))}
        </div>
      </FadeIn>
    </section>
  );
}

/* ── What's broken in most accounts ──────────────────────────────────── */

function Problems() {
  const problems = [
    {
      title: "Welcome flow sending one email",
      body: "Most brands send one generic welcome and stop. You're leaving the highest-intent moment in your customer journey completely untouched.",
    },
    {
      title: "No abandoned cart sequence",
      body: "60–70% of carts are abandoned. Without a proper sequence, that revenue is gone. With one, a significant portion comes back.",
    },
    {
      title: "Campaigns with no strategy",
      body: "Blasting your whole list the same email kills deliverability and trains subscribers to ignore you. Segmentation and send-time optimisation changes everything.",
    },
  ];

  return (
    <section className="bg-ink px-6 py-24 md:px-10 md:py-32">
      <div className="mx-auto max-w-3xl">
        <FadeIn>
          <div className="flex items-center gap-2.5 text-[11px] font-medium uppercase tracking-[0.24em] text-white/45">
            <Dot />
            Why your email isn't converting
          </div>
        </FadeIn>

        <div className="mt-12 space-y-10">
          {problems.map((p, i) => (
            <FadeIn key={p.title} delay={i * 0.07}>
              <div className="flex items-start gap-4">
                <Dot className="mt-2.5" />
                <div>
                  <h3 className="font-display tracking-display text-xl text-white md:text-2xl">
                    {p.title}
                  </h3>
                  <p className="mt-3 font-sans font-light leading-relaxed text-white/55">
                    {p.body}
                  </p>
                </div>
              </div>
            </FadeIn>
          ))}
        </div>
      </div>
    </section>
  );
}

/* ── What we do ───────────────────────────────────────────────────────── */

function Services() {
  const cards = [
    {
      title: "Flow rebuild",
      items: [
        "Welcome series (3 emails, conditional split new vs returning)",
        "Abandoned cart (4 variants by buyer history)",
        "Post-purchase (review + cross-sell)",
        "Browse abandonment",
        "Win-back",
      ],
    },
    {
      title: "Monthly campaigns",
      items: [
        "10–14 campaigns/month",
        "Segmented by behaviour",
        "A/B subject line testing",
        "Send-time optimisation",
        "Full copywriting included",
      ],
    },
    {
      title: "Klaviyo management",
      items: [
        "Full account audit",
        "List cleaning",
        "Deliverability monitoring",
        "Weekly performance report",
        "Monthly strategy call",
      ],
    },
  ];

  return (
    <section className="bg-carbon px-6 py-24 md:px-10 md:py-32">
      <div className="mx-auto max-w-6xl">
        <div className="grid gap-6 md:grid-cols-3">
          {cards.map((c, i) => (
            <FadeIn key={c.title} delay={i * 0.07}>
              <div className="h-full rounded-2xl border border-white/10 bg-ink p-8">
                <h3 className="font-display tracking-display text-xl text-white">{c.title}</h3>
                <ul className="mt-6 space-y-3 border-t border-white/10 pt-6">
                  {c.items.map((item) => (
                    <li key={item} className="flex items-start gap-3 text-sm text-white/70">
                      <Dot className="mt-1.5" />
                      <span className="font-light">{item}</span>
                    </li>
                  ))}
                </ul>
              </div>
            </FadeIn>
          ))}
        </div>
      </div>
    </section>
  );
}

/* ── What you get for £490/month ─────────────────────────────────────── */

function WhatYouGet() {
  const items = [
    "Full Klaviyo flow rebuild",
    "Monthly campaign management",
    "Copywriting included",
    "Segmentation setup",
    "Deliverability audit",
    "Weekly report",
    "Monthly strategy call",
    "No lock-in — cancel anytime",
  ];

  return (
    <section className="bg-ink px-6 py-24 md:px-10 md:py-32">
      <div className="mx-auto max-w-3xl">
        <FadeIn>
          <h2 className="font-display tracking-display text-3xl text-white md:text-4xl">
            Everything. No hidden extras<span className="text-volt">.</span>
          </h2>
        </FadeIn>

        <FadeIn delay={0.06}>
          <ul className="mt-10 grid gap-3 sm:grid-cols-2">
            {items.map((item) => (
              <li key={item} className="flex items-start gap-3 text-sm font-light text-white/70">
                <Dot className="mt-1.5" />
                {item}
              </li>
            ))}
          </ul>
        </FadeIn>

        <FadeIn delay={0.12}>
          <div className="mt-10 rounded-xl border-l-2 border-volt bg-carbon p-6">
            <p className="font-sans font-light leading-relaxed text-white/70">
              Most agencies charge £1,500–£3,000/month for this. We're offering
              3 brands the full service at £490 to build UK case studies. When
              those spots fill, the price goes up.
            </p>
          </div>
        </FadeIn>
      </div>
    </section>
  );
}

/* ── Results ──────────────────────────────────────────────────────────── */

function Results() {
  const cards = [
    {
      metric: "£262K",
      label: "Generated by a single welcome flow",
      context: "38.7% open rate · 71,059 delivered · Klaviyo, ecommerce brand UK",
    },
    {
      metric: "70%",
      label: "Average open rate across managed accounts",
      context: "vs 20–25% industry average · 99.99% deliverability",
    },
  ];

  return (
    <section className="bg-carbon px-6 py-24 md:px-10 md:py-32">
      <div className="mx-auto max-w-4xl">
        <FadeIn>
          <h2 className="font-display tracking-display text-3xl text-white md:text-4xl">
            Real flows, real numbers<span className="text-volt">.</span>
          </h2>
        </FadeIn>

        <div className="mt-12 grid gap-6 md:grid-cols-2">
          {cards.map((c, i) => (
            <FadeIn key={c.metric} delay={i * 0.07}>
              <div className="h-full rounded-2xl border border-white/10 bg-carbon p-8">
                <div className="font-display tracking-display text-5xl text-volt">{c.metric}</div>
                <div className="mt-5 font-sans font-light text-white">{c.label}</div>
                <div className="mt-2 text-sm text-white/45">{c.context}</div>
              </div>
            </FadeIn>
          ))}
        </div>

        <FadeIn delay={0.16}>
          <p className="mt-8 text-xs text-white/40">
            Results from live accounts. Your results will depend on list size,
            product, and market.
          </p>
        </FadeIn>
      </div>
    </section>
  );
}

/* ── FAQ ──────────────────────────────────────────────────────────────── */

function Faq() {
  const faqs = [
    {
      q: "Do I need a big email list?",
      a: "No. We've generated significant revenue from lists under 5,000. What matters is how the flows are built and how campaigns are segmented, not raw list size.",
    },
    {
      q: "What platform do you use?",
      a: "Klaviyo. It's the best ecommerce email platform available and what we specialise in exclusively.",
    },
    {
      q: "How quickly will I see results?",
      a: "Welcome and abandoned cart flows go live within the first two weeks. Most brands see attributed revenue from flows within 30 days.",
    },
    {
      q: "Is there a contract?",
      a: "No lock-in. Month-to-month. If we're not delivering, you can cancel. We're confident enough in the results to not need a contract.",
    },
    {
      q: "What if I already have flows set up?",
      a: "We audit what's there first. If your existing flows are performing well, we keep them. Usually there's significant room to improve — but we won't rebuild for the sake of it.",
    },
  ];

  return (
    <section className="bg-ink px-6 py-24 md:px-10 md:py-32">
      <div className="mx-auto max-w-3xl">
        <FadeIn>
          <h2 className="font-display tracking-display text-3xl text-white md:text-4xl">
            Questions<span className="text-volt">.</span>
          </h2>
        </FadeIn>

        <div className="mt-10 divide-y divide-white/10 border-t border-white/10">
          {faqs.map((f, i) => (
            <FadeIn key={f.q} delay={(i % 5) * 0.05}>
              <details className="group py-6">
                <summary className="flex cursor-pointer list-none items-center justify-between gap-4 [&::-webkit-details-marker]:hidden">
                  <span className="font-display tracking-display text-lg text-white">{f.q}</span>
                  <ChevronDown className="h-4 w-4 shrink-0 text-white/45 transition-transform group-open:rotate-180" />
                </summary>
                <p className="mt-4 max-w-[60ch] font-sans font-light leading-relaxed text-white/55">
                  {f.a}
                </p>
              </details>
            </FadeIn>
          ))}
        </div>
      </div>
    </section>
  );
}

/* ── Final CTA ────────────────────────────────────────────────────────── */

function FinalCta() {
  return (
    <section className="bg-volt px-6 py-24 text-center md:px-10 md:py-32">
      <FadeIn>
        <div className="mx-auto max-w-2xl">
          <h2 className="font-display tracking-display text-3xl font-semibold text-ink md:text-4xl">
            3 spots. £490/month. No contract.
          </h2>
          <p className="mx-auto mt-5 max-w-md font-sans font-light text-ink/60">
            When these fill, the price goes up. Book a free 20-minute call to
            see if your brand is a fit.
          </p>
          <a
            href={CALENDLY_PLACEHOLDER}
            target="_blank"
            rel="noopener noreferrer"
            onClick={onCtaClick}
            className="group mt-8 inline-flex items-center gap-2 rounded-full bg-ink px-8 py-4 font-display tracking-display text-base font-semibold text-white transition-opacity hover:opacity-90"
          >
            Book your free call
            <ArrowRight className="h-4 w-4 transition-transform group-hover:translate-x-0.5" />
          </a>
          <p className="mt-5 text-sm text-ink/60">
            No pitch. No hard sell. Just an honest look at what your email is
            leaving behind.
          </p>
        </div>
      </FadeIn>
    </section>
  );
}

/* ── Footer ───────────────────────────────────────────────────────────── */

function MinimalFooter() {
  return (
    <footer className="bg-ink px-6 py-10 text-center">
      <p className="text-xs text-white/45">© 2026 EraLean · asaf@eralean.com</p>
    </footer>
  );
}

export default function EmailLp() {
  return (
    <div className="bg-ink text-white">
      <Header />
      <main>
        <Hero />
        <ProofBar />
        <Problems />
        <Services />
        <WhatYouGet />
        <Results />
        <Faq />
        <FinalCta />
      </main>
      <MinimalFooter />
    </div>
  );
}
